#
# This script was developed for SweetTutos Tutorials
# www.sweettutos.wordpress.com
#
include $(GNUSTEP_MAKEFILES)/common.make
# make a simple program in Objective-C, call it SweetTutos
TOOL_NAME = Level3
# The implementation Objective-C file which is going to be compiled
Level3_OBJC_FILES = main.m MrHiggie.m
# Header files of your project
Level3_HEADER_FILES = MrHiggie.h DayOfWeek.h
#//here goes all header files (.h). For the moment, on n'en a pas.
# Define compilation flags
ADDITIONAL_CPPFLAGS = -Wall -Wno-import
# Include rules for creating a command line tool for Objective-C
include $(GNUSTEP_MAKEFILES)/tool.make