/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddFriend.java
 *
 * Created on 02.01.2014., 22:20:30
 */

package pagru_v05;

import java.net.*;
import java.io.*;

/**
 *
 * @author MadHatress
 */
public class AddFriend extends javax.swing.JDialog {

    private MainWindow mainWindow;
	
    /** Creates new form AddFriend */
    public AddFriend(MainWindow _mainWindow) {            
        initComponents();
        setTitle("Add Friend");
        mainWindow = _mainWindow;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FriendsMail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FriendsName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FriendsSurname = new javax.swing.JTextField();
        AddFriendAddButton = new javax.swing.JButton();
        AddFriendCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("E-mail address:");

        FriendsMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendsMailActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
//TODO edited za igranje
        //        jLabel2.setText("Name:");
        jLabel2.setText("Username:");

        FriendsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendsNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Surname:");

        FriendsSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendsSurnameActionPerformed(evt);
            }
        });

        AddFriendAddButton.setText("Add");
        AddFriendAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFriendAddButtonActionPerformed(evt);
            }
        });

        AddFriendCancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FriendsMail, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FriendsName, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FriendsSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(AddFriendAddButton)
                        .addGap(76, 76, 76)
                        .addComponent(AddFriendCancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FriendsMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FriendsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FriendsSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFriendCancelButton)
                    .addComponent(AddFriendAddButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FriendsMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendsMailActionPerformed
    }//GEN-LAST:event_FriendsMailActionPerformed

    private void FriendsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendsNameActionPerformed
    }//GEN-LAST:event_FriendsNameActionPerformed

    private void FriendsSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendsSurnameActionPerformed
    }//GEN-LAST:event_FriendsSurnameActionPerformed

    private void AddFriendAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
    	String myUsername = mainWindow.getMyUsername();
    	String FriendUsername = FriendsName.getText().toString(); 
    	if ( !(FriendUsername.equals("")) && !(FriendUsername.equals(myUsername)) ) /* ako nije prazan string (username ne moze biti "") i ako ne pokusavam dodat samog sebe za frenda */
    		mainWindow.send("ADDFRIEND" + " " + myUsername + " " + FriendUsername);
    }//GEN-LAST:event_SendButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFriendAddButton;
    private javax.swing.JButton AddFriendCancelButton;
    private javax.swing.JTextField FriendsMail;
    private javax.swing.JTextField FriendsName;
    private javax.swing.JTextField FriendsSurname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
